### ISSUE TITLE
Document multi-target setup

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/docsite#263]
As mentioned in https://github.com/DioxusLabs/dioxus/issues/2291, we currently don't have great documentation about setting up a project that targets multiple platforms.

A multi platform setup can have one feature per platform:

```toml
dioxus = { version = "0.5" }

[features]
desktop = ["dioxus/desktop"]
liveview = ["dioxus/liveview"]
fullstack = ["dioxus/fullstack"]
server = ["dioxus/axum"]
web = ["dioxus/web"]
```

We should also document or link to documentation about several issues you are likely to run into with a multi target setup:
- WASM tokio incompatibility
- Wasm-bindgen desktop incompatibility
- Setting up target specific features
