### ISSUE TITLE
Some code blocks are empty even though they have content in the md files.

### ISSUE THREAD

**Issue by sknauff** [DioxusLabs/docsite#355]
Looking through the HotDog tutorial, I found two code blocks that have values in the corresponding md files, but are parsed as empty code blocks.

The first one is on the [bundle](https://dioxuslabs.com/learn/0.6/guide/bundle#automating-dx-bundle-with-json-mode) page of the tutorial:

![](https://github.com/user-attachments/assets/7e62d3ab-9f6e-4f4f-85f8-68fc85f4c900)

This [should contain](https://github.com/DioxusLabs/docsite/blob/ca57b044706c3953b159b2ba8d30e280cf5ed3ea/docs-src/0.6/src/guide/bundle.md?plain=1#L210):

```sh
{"timestamp":"   9.927s","level":"INFO","message":"Bundled app successfully!","target":"dx::cli::bundle"}
{"timestamp":"   9.927s","level":"INFO","message":"App produced 2 outputs:","target":"dx::cli::bundle"}
{"timestamp":"   9.927s","level":"DEBUG","message":"Bundling produced bundles: [\n    Bundle {\n        package_type: MacOsBundle,\n        bundle_paths: [\n            \"/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/macos/HotDog.app\",\n        ],\n    },\n    Bundle {\n        package_type: Dmg,\n        bundle_paths: [\n            \"/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/dmg/HotDog_0.1.0_aarch64.dmg\",\n        ],\n    },\n]","target":"dx::cli::bundle"}
{"timestamp":"   9.927s","level":"INFO","message":"app - [/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/macos/HotDog.app]","target":"dx::cli::bundle"}
{"timestamp":"   9.927s","level":"INFO","message":"dmg - [/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/dmg/HotDog_0.1.0_aarch64.dmg]","target":"dx::cli::bundle"}
{"timestamp":"   9.927s","level":"DEBUG","json":"{\"BundleOutput\":{\"bundles\":[\"/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/macos/HotDog.app\",\"/Users/jonkelley/Development/Tinkering/06-demos/hot_dog/target/dx/hot_dog/bundle/macos/bundle/dmg/HotDog_0.1.0_aarch64.dmg\"]}}","target":"dx"}
```

Similarly, the second one is on the [deploy](https://dioxuslabs.com/learn/0.6/guide/deploy#continuous-deployment) page of the tutorial:

![](https://github.com/user-attachments/assets/37237bf3-1668-4fd2-ad07-4f45ddc4f06e)

This [should contain](https://github.com/DioxusLabs/docsite/blob/ca57b044706c3953b159b2ba8d30e280cf5ed3ea/docs-src/0.6/src/guide/deploy.md?plain=1#L150):

```yml
name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```
