### ISSUE TITLE
Cleanup CSS

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/docsite#413]
Separate `dxp.css` into multiple different organized css files. Ideally, we could also use SCSS (with hot reloading) for it's ability to have CSS child ids/classes within a parent scope. E.g.

```scss
#container {
    background-color: red;
   
    #text {
         color: blue;
    }
}
```
